---
title: "Exam Out Preparation"
author: "Marc Kaufmann"
date: "8/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Load the session files
# For each session:
# - Give every person in the survey a new unique name from some vector of unique names
# - merge this onto the other days for that same session\
# - drop the mturk_id

names <- c("Adam", "András", "Andrea", "Attila", "Bea", "Béla", "Boglárka", "Botond", "Csaba", "Csilla", "Dorit", "Dorottya", "Emese", "Enikő", "Erzsébet", "Géza", "György", "Ildikó", "Imre", "István", "János", "József", "Károly", "Katalin", "Kata", "Lajos", "László", "Margit", "Mária", "Márk", "Márton", "Mátyás", "Melinda", "Orsolya", "Piroska", "Réka", "Robert", "Sándor", "Tamás", "Tünde", "Zoltán", "Zsigmond", "Zsófia", "Zsuzsanna")

library(tidyverse)

data_dir <- "/home/marc/Git/kutat/R-Coding/exam-out/"

read_session <- function(prefix) {
  survey <- read_csv(paste(data_dir, prefix, "_survey_day1.csv", sep=""))
  day1 <- read_csv(paste(data_dir, prefix, "_day1.csv", sep=""))
  day2 <- read_csv(paste(data_dir, prefix, "_day2.csv", sep=""))
  list("survey"=survey, "day1"=day1, "day2"=day2)
}

session2 <- read_session("session2")
session3 <- read_session("session3")

session_replace_day1 <- function(session, day1) {
  return(list("survey"=session$survey,
       "day2"=session$day2,
       "day1"=day1))
}

get_names_session <- function(session) {
  get_names_day <- function(day) {
    left_join(day,
              session$survey %>% select("mturk_id", "name"),
              by=c("mturk_id"))
  }
  newday1 <- get_names_day(session$day1)
  newday2 <- get_names_day(session$day2)
  list("survey"=session$survey, "day1"=newday1, "day2"=newday2)
}

drop_mturk_id <- function(session) {
  session$survey <- select(session$survey, -mturk_id)
  session$day1 <- select(session$day1, -mturk_id)
  session$day2 <- select(session$day2, -mturk_id)
  session
}

write_session <- function(session, prefix) {
  write_csv(session$survey, paste(data_dir, prefix, "_survey_day1_names.csv", sep=""))
  write_csv(session$day1, paste(data_dir, prefix, "_day1_names.csv", sep=""))
  write_csv(session$day2, paste(data_dir, prefix, "_day2_names.csv", sep=""))
}

anonymize_session <- function(session) {
  # create name column with unique name by ID
  session$survey$name <- sample(names, nrow(session$survey))
  # add this same name for the same mturk_id in day1 and day2
  session <- get_names_session(session)
  # Drop the mturk_id column
  session <- drop_mturk_id(session)
  session
}

replace_choices_by_treatment_and_control <- function(session, session_string) {
  # We want data that has batch{1,2,3}{treatment,control}, i.e. six new columns that are differences
  if(session_string == "session1") {
    newday1 <- session$day1 %>%
      mutate(batch1_control= answer_2 - answer_1) %>%
      mutate(batch1_treatment= answer_4 - answer_3) %>%
      mutate(batch2_control= answer_7 - answer_6) %>%
      mutate(batch2_treatment= answer_9 - answer_7) %>%
      mutate(batch3_control= answer_11 - answer_10) %>%
      mutate(batch3_treatment= answer_13 - answer_12) %>%
      mutate(number_of_choices=13)
  } else {
    newday1 <- session$day1 %>%
      mutate(batch1_control= answer_2 - answer_1) %>%
      mutate(batch1_treatment= answer_4 - answer_3) %>%
      mutate(batch2_control= answer_9 - answer_8) %>%
      mutate(batch2_treatment= answer_11 - answer_10) %>%
      mutate(batch3_control= answer_13 - answer_12) %>%
      mutate(batch3_treatment= answer_15 - answer_14) %>%
      mutate(number_of_choices=15)
  }
  
  newday1 <- newday1 %>%
    select(-starts_with("choice_")) %>%
    select(-starts_with("answer_")) %>%
    select(-starts_with("rational_switch")) 
    # select(-starts_with("has_single_switch"))
    
  return(session_replace_day1(session, newday1))
}

for(session_string in list("session1", "session2", "session3")) {
  read_session(session_string) %>%
    anonymize_session() %>%
    replace_choices_by_treatment_and_control(session_string) %>%
    write_session(session_string)
}
```

